### ISSUE TITLE
Test-drive the Heroku HOWTO

### ISSUE THREAD

**Issue by boutell** [punkave/apostrophe-documentation#42]
http://apostrophecms.org/docs/tutorials/howtos/deploying-apostrophe-in-the-cloud.html

Let me know what's good, what's bad, what's unclear, what's buggy... the target audience is anybody who's built a few Apostrophe sites, so don't feel it's your job to somehow get what I didn't say. Thanks!

**Comment by alexgleason** [comment]
Awesome, I use Dokku for everything so this should work with that, too, if it works with Heroku.

For reference: I've written a [tutorial](https://blog.candlewaster.co/how-to-deploy-a-wagtail-site-to-dokku/) for deploying Wagtail to Dokku.
